F3FChrono/web/administrator/celery_progress/urls.py
from django.urls import re_path
from . import views

app_name = 'celery_progress'
urlpatterns = [
    re_path(r'^(?P<task_id>[\w-]+)/$', views.get_progress, name='task_status')
]

F3FChrono/web/administrator/urls.py
#
# This file is part of the F3FChrono distribution (https://github.com/jomarin38/F3FChrono).
# Copyright (c) 2021 Sylvain DAVIET, Joel MARIN.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

from django.urls import path, re_path, include

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login_f3f_admin', views.login_f3f_admin, name='login_f3f_admin'),
    path('logout_f3f_admin', views.logout_f3f_admin, name='logout_f3f_admin'),
    path('create_new_event', views.create_new_event, name='create_new_event'),
    path('load_from_f3x_vault', views.load_from_f3x_vault, name='load_from_f3x_vault'),
    path('load_from_scratch', views.load_from_scratch, name='load_from_scratch'),
    path('manage_event', views.manage_event, name='manage_event'),
    path('set_competitor_presence', views.set_competitor_presence, name='set_competitor_presence'),
    path('remove_competitor', views.remove_competitor, name='remove_competitor'),
    path('edit_run_time', views.edit_run_time, name='edit_run_time'),
    path('set_time', views.set_time, name='set_time'),
    path('new_pilot_input', views.new_pilot_input, name='new_pilot_input'),
    path('register_new_pilot', views.register_new_pilot, name='register_new_pilot'),
    path('cancel_round', views.cancel_round, name='cancel_round'),
    path('validate_round', views.validate_round, name='validate_round'),
    path('delete_event', views.delete_event, name='delete_event'),
    path('do_delete_event', views.do_delete_event, name='do_delete_event'),
    path('manage_round', views.manage_round, name='manage_round'),
    path('give_refly', views.give_refly, name='give_refly'),
    path('give_penalty', views.give_penalty, name='give_penalty'),
    path('give_zero', views.give_zero, name='give_zero'),
    path('download_csv', views.download_csv, name='download_csv'),
    path('download_pilots_as_csv', views.download_pilots_as_csv, name='download_pilots_as_csv'),
    path('export_round_f3x_vault', views.export_round_f3x_vault, name='export_round_f3x_vault'),
    path('login_to_export_round_f3x_vault', views.login_to_export_round_f3x_vault,
         name='login_to_export_round_f3x_vault'),
    path('auto_export_round_f3x_vault', views.auto_export_round_f3x_vault,
             name='auto_export_round_f3x_vault'),
    path('export_event_f3x_vault', views.export_event_f3x_vault, name='export_event_f3x_vault'),
    path('login_to_export_event_f3x_vault', views.login_to_export_event_f3x_vault,
         name='login_to_export_event_f3x_vault'),
    path('define_bibs', views.define_bibs, name='define_bibs'),
    path('do_define_bibs', views.do_define_bibs, name='define_bibs'),
    path('define_fly_order', views.define_fly_order, name='define_fly_order'),
    path('do_define_fly_order', views.do_define_fly_order, name='define_fly_order'),
    re_path(r'^celery-progress/', include('celery_progress.urls', namespace="celery_progress")),
]

F3FChrono/web/f3franking/urls.py
#
# This file is part of the F3FChrono distribution (https://github.com/jomarin38/F3FChrono).
# Copyright (c) 2021 Sylvain DAVIET, Joel MARIN.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('event_view', views.event_view, name='event_view'),
    path('round_view', views.round_view, name='round_view'),
    path('is_alive', views.is_alive, name='is_alive')
]

F3FChrono/web/webinterface/urls.py
from django.contrib import admin
from django.urls import include,path
import os

public_only = os.getenv('PUBLIC_ONLY', 'False').lower() in ('true', '1', 't')
private_only = os.getenv('PRIVATE_ONLY', 'False').lower() in ('true', '1', 't')

print('public_only={}'.format(public_only))
print('private_only={}'.format(private_only))

urlpatterns = []

if not private_only :
    urlpatterns += [
        path('f3franking/', include('F3FChrono.web.f3franking.urls'))
    ]

if not public_only :
    urlpatterns += [
        path('administrator/', include('F3FChrono.web.administrator.urls')),
        path('admin/', admin.site.urls),
    ]

F3FChrono/web/administrator/models.py
#
# This file is part of the F3FChrono distribution (https://github.com/jomarin38/F3FChrono).
# Copyright (c) 2021 Sylvain DAVIET, Joel MARIN.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

from django.db import models

# Create your models here.

F3FChrono/web/administrator/celery_progress/views.py
import json
from django.http import HttpResponse
from celery.result import AsyncResult
from celery_progress.backend import Progress
from django.views.decorators.cache import never_cache

@never_cache
def get_progress(request, task_id):
    progress = Progress(AsyncResult(task_id))
    return HttpResponse(json.dumps(progress.get_info()), content_type='application/json')

F3FChrono/web/administrator/views.py
#
# This file is part of the F3FChrono distribution (https://github.com/jomarin38/F3FChrono).
# Copyright (c) 2021 Sylvain DAVIET, Joel MARIN.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from django.template import RequestContext
from django.views.decorators.cache import never_cache

from F3FChrono.data.Chrono import Chrono
from F3FChrono.data.Run import Run
from F3FChrono.data.dao.CompetitorDAO import CompetitorDAO
from F3FChrono.data.dao.EventDAO import EventDAO
from F3FChrono.data.dao.RoundDAO import RoundDAO
from F3FChrono.data.dao.FlyOrderDAO import FlyOrderDAO
from F3FChrono.data.web.ResultPage import ResultPage
from F3FChrono.data.web.ResultTable import ResultTable
from F3FChrono.data.web.Header import Header
from F3FChrono.data.web.Line import Line
from F3FChrono.data.web.Cell import Cell
from F3FChrono.data.web.Link import Link
from F3FChrono.data.web.Utils import Utils
from F3FChrono.data.Event import Event
from F3FChrono.data.Pilot import Pilot
from F3FChrono.data.Round import Round
from F3FChrono.chrono import ConfigReader
from F3FChrono.web.administrator.cached_credentials import CachedCredentials

from F3FChrono.web.administrator.tasks import f3x_vault_export_round_task
from F3FChrono.web.administrator.tasks import f3x_vault_export_event_task

import csv


def sign_in(request):
    if not request.user.is_authenticated:

        return render(request, 'login_template.html',
                                  {'next' : request.GET.get('next')}
                                  )

    else:
        return HttpResponse('Authenticated user !')


def login_f3f_admin(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        # Redirect to a success page.
        return redirect(request.GET.get('next'))
    else:
        return redirect('sign_in')


def logout_f3f_admin(request):
    logout(request)
    return HttpResponse('<p>Successfully logged out !</p>')


def create_new_event(request):
    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % ('sign_in', request.path))

    Utils.set_port_number(request.META['SERVER_PORT'])

    return render(request, 'new_event_template.html', {})


def new_pilot_input(request):
    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % ('sign_in', request.path))

    Utils.set_port_number(request.META['SERVER_PORT'])

    return render(request, 'new_pilot_template.html', {'event_id': request.GET.get('event_id')})


def set_time(request):
    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % ('sign_in', request.path))

    Utils.set_port_number(request.META['SERVER_PORT'])

    return render(request, 'edit_time_template.html', {'event_id': request.GET.get('event_id'),
                                                       'round_number': request.GET.get('round_number'),
                                                       'bib_number': request.GET.get('bib_number')})


def cancel_round(request):
    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % ('sign_in', request.path))

    Utils.set_port_number(request.META['SERVER_PORT'])

    event_id = request.GET['event_id']
    round_number = request.GET['round_number']

    f3f_round = RoundDAO().get_from_ids(event_id, round_number, fetch_runs=True)
    f3f_round.do_cancel_round()

    return HttpResponseRedirect('manage_event?event_id='+event_id)


def validate_round(request):
    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % ('sign_in', request.path))

    Utils.set_port_number(request.META['SERVER_PORT'])

    event_id = request.GET['event_id']
    round_number = request.GET['round_number']

    f3f_round = RoundDAO().get_from_ids(event_id, round_number, fetch_runs=True)
    f3f_round.validate_round(insert_database=True)

    return HttpResponseRedirect('manage_event?event_id='+event_id)


def register_new_pilot(request):

    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % ('sign_in', request.path))

    Utils.set_port_number(request.META['SERVER_PORT'])

    pilot_name = request.POST['pilotname']
    pilot_first_name = request.POST['pilotfirstname']
    pilot_fai_id = request.POST['pilotfaiid']
    pilot_national_id = request.POST['pilotnationalid']
    pilot_f3xvault_id = request.POST['pilotf3xvaultid']

    event_id = request.GET.get('event_id')
    event = EventDAO().get(event_id, fetch_competitors=True)

    pilot = Pilot(name=pilot_name,
                  first_name=pilot_first_name,
                  f3x_vault_id=pilot_f3xvault_id,
                  national_id=pilot_national_id,
                  fai_id=pilot_fai_id
                  )

    bib_number = event.next_available_bib_number()

    competitor = event.register_pilot(pilot, bib_number)
    CompetitorDAO().insert(competitor)

    return HttpResponseRedirect('manage_event?event_id='+event_id)


def edit_run_time(request):

    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % ('sign_in', request.path))

    Utils.set_port_number(request.META['SERVER_PORT'])

    flight_time = float(request.POST['flight_time'])

    event_id = int(request.GET.get('event_id'))
    round_number = int(request.GET.get('round_number'))
    bib_number = int(request.GET.get('bib_number'))

    event = EventDAO().get(event_id, fetch_competitors=True)
    f3f_round = RoundDAO().get_from_ids(event_id, round_number, fetch_runs=True)

    chrono = Chrono()
    chrono.run_time = flight_time

    run = Run()
    run.competitor = event.get_competitor(bib_number)
    run.penalty = 0
    run.chrono = chrono
    run.valid = True

    f3f_round.add_run_from_web(run)

    RoundDAO().update(f3f_round)

    return HttpResponseRedirect('manage_round?event_id='+str(event_id)+'&round_number='+str(round_number))


def delete_event(request):
    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % ('sign_in', request.path))

    Utils.set_port_number(request.META['SERVER_PORT'])

    return render(request, 'event_deletion_template.html', {'event_id': request.GET.get('event_id')})


def do_delete_event(request):

    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % ('sign_in', request.path))

    Utils.set_port_number(request.META['SERVER_PORT'])

    event_id = request.GET.get('event_id')
    EventDAO().delete(EventDAO().get(event_id))

    return redirect('index')


def load_from_f3x_vault(request):
    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % ('sign_in', request.path))

    Utils.set_port_number(request.META['SERVER_PORT'])

    if ('username' in request.POST) and ('password' in request.POST) and ('F3X_vault_id' in request.POST):

        f3x_username = request.POST["username"]
        f3x_password = request.POST["password"]

        f3x_event_id = request.POST["F3X_vault_id"]

        event = Event.from_f3x_vault(f3x_username, f3x_password, f3x_event_id)

        event.id = EventDAO().insert(event)

        for bib, competitor in event.get_competitors().items():
            CompetitorDAO().insert(competitor)

        for f3f_round in event.rounds:
            RoundDAO().insert(f3f_round)

        return redirect('index')

    else:

        return HttpResponse('<p>Invalid parameters !')


def load_from_scratch(request):
    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % ('sign_in', request.path))

    Utils.set_port_number(request.META['SERVER_PORT'])
    try:
        csv_file = request.FILES["csv_file"]
        event_name = request.POST["eventname"]
        event_location = request.POST["eventlocation"]
        event_start_date = request.POST["startdate"]
        event_end_date = request.POST["enddate"]

        event = Event.from_csv(event_name, event_location, event_start_date, event_end_date, csv_file)

        event.id = EventDAO().insert(event)

        for bib, competitor in event.get_competitors().items():
            CompetitorDAO().insert(competitor)

        return redirect('index')

    except Exception as e:
        return HttpResponse('<p>Invalid parameters !')


def manage_event(request):
    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % ('sign_in', request.path))

    Utils.set_port_number(request.META['SERVER_PORT'])

    event_id = request.GET.get('event_id')

    event = EventDAO().get(event_id=event_id, fetch_competitors=True, fetch_rounds=True, fetch_runs=True)

    page = ResultPage(title=event.name, authenticated=request.user.is_authenticated)

    table = ResultTable(title='', css_id='ranking')

    header = Header(name=Link('Delete event', 'delete_event?event_id='+event_id))
    table.set_header(header)

    page.add_table(table)

    table = ResultTable(title='', css_id='ranking')

    header = Header(name=Link('Export bib numbers', 'download_pilots_as_csv?event_id=' + event_id))
    table.set_header(header)

    page.add_table(table)

    table = ResultTable(title='', css_id='ranking')

F3FChrono/web/administrator/templates/define_bibs_template.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
<head>
<style type="text/css">
body {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}
input {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  box-sizing: border-box;
}
input:focus {
  background-color: lightblue;
}
input[type=button], input[type=submit], input[type=reset] {
  background-color: #4CAF50;
  border: none;
  color: white;
  padding: 16px 32px;
  text-decoration: none;
  margin: 4px 2px;
  cursor: pointer;
}
</style>
</head>
<body>
    <h1>Import bibs from csv file</h1>
    <form action="do_define_bibs?event_id={{event_id}}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="username_label">F3X Vault username : </label>
        <input id="username_field" type="text" name="username" value="">
        <br/>
        <label for="password_label">F3X Vault Password : </label>
        <input id="password_field" type="password" name="password" value="">
        <br/>
        <input type="file" name="csv_file" id="csv_file" required="True" class="form-control">
        <br/>
        <input type="submit" value="Define bibs !">
    </form>
</body>

F3FChrono/web/administrator/templates/define_fly_order_template.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
<head>
<style type="text/css">
body {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}
input {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  box-sizing: border-box;
}
input:focus {
  background-color: lightblue;
}
input[type=button], input[type=submit], input[type=reset] {
  background-color: #4CAF50;
  border: none;
  color: white;
  padding: 16px 32px;
  text-decoration: none;
  margin: 4px 2px;
  cursor: pointer;
}
</style>
</head>
<body>
    <h1>Import bibs from csv file</h1>
    <form action="do_define_fly_order?event_id={{event_id}}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="csv_file" id="csv_file" required="True" class="form-control">
        <br/>
        <input type="submit" value="Define fly order !">
    </form>
</body>

F3FChrono/web/administrator/templates/display_progress.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>F3X Vault upload progress</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
        <script src="{% static 'jquery.min.js' %}"></script>
        <script src="{% static 'popper.min.js' %}"></script>
        <script src="{% static 'bootstrap.min.js' %}"></script>
        <style>
            .nasa-image {
                max-width: 100%;
                max-height: 230px;
                padding-bottom: 5px;
            }
        </style>
    </head>
    <body>
        <!--{% load static %}-->
        <div class="bg-dark text-white text-center">
            <h1>F3X vault upload</h1>
        </div>

        <div class="container-fluid">
            <div class="row align-items-end">
                <div class="col-sm-3">
                    <div class='progress-wrapper'>
                        <div id="progress-bar{{ key }}" class='progress-bar' style="background-color: #68a9ef; width: 0%;">&nbsp;</div>
                    </div>
                    <div id="progress-bar{{ key }}-message">Waiting for progress to start...</div>
                </div>
            </div>
        </div>
    </body>
</html>
<!-- celery logic -->
<script src="{% static 'celery_progress/celery_progress.js' %}"></script>

<script>
    function customProgress(progressBarElement, progressBarMessageElement, progress) {
        barIdentifier = progressBarElement.id.substring(12)

        if(progress.current == 0 && progress.total == 100){
            progressMessage = ""
        } else {

            taskNumber = parseInt(progress.current)+1
            taskPercentage = taskNumber / progress.total * 100

            progressBarElement.style.backgroundColor = "#68a9ef"
            progressBarElement.style.width = taskPercentage + "%"
            progressBarMessageElement.className = "alert alert-info"
            progressMessage = "Currently sending run " + taskNumber + " of " + progress.total
        }

        progressBarMessageElement.innerHTML = (
            progressMessage
        );
    }
</script>

<script src="{% static 'celery_progress/celery_progress.js' %}"></script>


<script>
    document.addEventListener("DOMContentLoaded", function () {
        var progressUrl = "{% url 'celery_progress:task_status' key %}";
        CeleryProgressBar.initProgressBar(progressUrl, {
            onProgress: customProgress,
            progressBarId: "progress-bar{{ key }}",
            progressBarMessageId: "progress-bar{{ key }}-message"
        });
    });
</script>

F3FChrono/web/administrator/templates/edit_time_template.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
<head>
<style type="text/css">
body {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}
input {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  box-sizing: border-box;
}
input:focus {
  background-color: lightblue;
}
input[type=button], input[type=submit], input[type=reset] {
  background-color: #4CAF50;
  border: none;
  color: white;
  padding: 16px 32px;
  text-decoration: none;
  margin: 4px 2px;
  cursor: pointer;
}
</style>
</head>
<body>
    <h1>Edit time for pilot {{bib_number}} :</h1>
        <form action="edit_run_time?event_id={{event_id}}&round_number={{round_number}}&bib_number={{bib_number}}" method="post" >
        {% csrf_token %}
        <label for="flight_time_label">Flight time : </label>
        <input id="flight_time_field" type="text" name="flight_time" value="">
        <br/>
        <input type="submit" value="Validate !">
    </form>
</body>

F3FChrono/web/administrator/templates/event_deletion_template.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
<head>
<style type="text/css">
body {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}
input {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  box-sizing: border-box;
}
input:focus {
  background-color: lightblue;
}
input[type=button], input[type=submit], input[type=reset] {
  background-color: #ff5050;
  border: none;
  color: white;
  padding: 16px 32px;
  text-decoration: none;
  margin: 4px 2px;
  cursor: pointer;
}
</style>
</head>
<body>
    <h1>Are you sure you want to delete this event ?</h1>
    <form action="do_delete_event?event_id={{event_id}}" method="post" >
        {% csrf_token %}
        <input type="submit" value="Delete !">
    </form>
    <a href="manage_event?event_id={{event_id}}">Cancel</a>
</body>

F3FChrono/web/administrator/templates/event_f3x_vault_export_template.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
<head>
<style type="text/css">
body {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}
input {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  box-sizing: border-box;
}
input:focus {
  background-color: lightblue;
}
input[type=button], input[type=submit], input[type=reset] {
  background-color: #4CAF50;
  border: none;
  color: white;
  padding: 16px 32px;
  text-decoration: none;
  margin: 4px 2px;
  cursor: pointer;
}
</style>
</head>
<body>
    <h1>Please provide F3X Vault credentials :</h1>
        <form action="export_event_f3x_vault?event_id={{event_id}}" method="post" >
        {% csrf_token %}
        <label for="username_label">F3X Vault username : </label>
        <input id="username_field" type="text" name="username" value="">
        <br/>
        <label for="password_label">F3X Vault Password : </label>
        <input id="password_field" type="password" name="password" value="">
        <br/>
        <label for="start_round_label">First round : </label>
        <input id="start_round_field" type="text" name="start_round" value="{{first_round}}">
        <br/>
        <label for="end_round_label">Last round : </label>
        <input id="end_round_field" type="text" name="end_round" value="{{last_round}}">
        <br/>
        <input type="submit" value="Export to F3X Vault !">
    </form>
</body>

F3FChrono/web/administrator/templates/login_template.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
<head>
<style type="text/css">
body {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}
input {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  box-sizing: border-box;
}
input:focus {
  background-color: lightblue;
}
input[type=button], input[type=submit], input[type=reset] {
  background-color: #4CAF50;
  border: none;
  color: white;
  padding: 16px 32px;
  text-decoration: none;
  margin: 4px 2px;
  cursor: pointer;
}
</style>
</head>
<body>
    <h1>Please log in to continue</h1>
    {% if next %}
    <form action="login_f3f_admin?next={{next}}" method="post" >
    {%else%}
    <form action="login_f3f_admin" method="post">
    {% endif %}
        {% csrf_token %}
        <label for="username_label">Username : </label>
        <input id="username_field" type="text" name="username" value="">
        <br/>
        <label for="password_label">Password : </label>
        <input id="password_field" type="password" name="password" value="">
        <br/>
        <input type="submit" value="Sign in !">
    </form>
</body>

F3FChrono/web/administrator/templates/new_event_template.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
<head>
<style type="text/css">
body {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}
input {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  box-sizing: border-box;
}
input:focus {
  background-color: lightblue;
}
input[type=button], input[type=submit], input[type=reset] {
  background-color: #4CAF50;
  border: none;
  color: white;
  padding: 16px 32px;
  text-decoration: none;
  margin: 4px 2px;
  cursor: pointer;
}
</style>
</head>
<body>
    <h1>Create new event from F3X Vault</h1>
    <form action="load_from_f3x_vault" method="post">
        {% csrf_token %}
        <label for="username_label">F3X Vault username : </label>
        <input id="username_field" type="text" name="username" value="">
        <br/>
        <label for="password_label">F3X Vault Password : </label>
        <input id="password_field" type="password" name="password" value="">
        <br/>
        <label for="F3X_vault_id_label">F3X Vault Event ID : </label>
        <input id="F3X_vault_id_field" type="text" name="F3X_vault_id" value="">
        <br/>
        <input type="submit" value="Load from F3X Vault !">
    </form>
    <h1>Create new event from scratch</h1>
    <form action="load_from_scratch" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="eventname_label">Event name : </label>
        <input id="eventname_field" type="text" name="eventname" value="">
        <br/>
        <label for="event_location_label">Event location : </label>
        <input id="event_location_field" type="text" name="eventlocation" value="">
        <br/>
        <label for="start_date_label">Start date (dd/mm/yy) : </label>
        <input id="start_date_field" type="text" name="startdate" value="">
        <br/>
        <label for="end_date_label">End date (dd/mm/yy) : </label>
        <input id="end_date_field" type="text" name="enddate" value="">
        <br/>
        <input type="file" name="csv_file" id="csv_file" required="True" class="form-control">
        <br/>
        <input type="submit" value="Create event !">
    </form>
</body>